name: 'Create Windows Executable'
description: 'Create an executable for windows when files are updated'
inputs: 
  path_to_UI: 
    description: 'Github Directory containing relevant files such as pyinstaller_script.py, UI, Pipeline, etc'
    required: True
    default: ./UserInterfaceV2
  spec:
    description: 'File path to .spec file'
    required: False
    default: ""
  requirements: 
    description: 'File path to requirements.txt'
    required: False
outputs:
  output:
    description: 'Pyinstaller Output'
runs: 
  using: 'docker'
  image: './wine_exe_Dockerfile'
  args: 
    - ${{ inputs.path_to_UI }}
    - ${{ inputs.spec }}
    - ${{ inputs.requirements }}
