name: Docker-tests
defaults:
  run:
    working-directory: ./
on:
  push:
    branches:
      - "*"

jobs:
  auto-ccs:
    runs-on: ubuntu-latest
    container: anubhav0fnu/autoccs
    steps:
      - name: Run help
        run: |
          docker run anubhav0fnu/autoccs python autoCCS.py --h
