name: Pyinstaller Windows Executable Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'Step 1 - Create a temporary artifact downloads folder'
      run: mkdir downloadsX

    - name: Step 2 - Create artifact
      uses: ./.github/actions
      with:
        path: .
    - name: 'Step 3 Upload artifact'
      uses: actions/upload-artifact@v3
      with:
        name: "Windows Exe"
        path: /home/runner/work/ion-mob-ms/ion-mob-ms/dist/*
      # - name: 'Reconnect to action repo'
      #   uses: actions/checkout@v3 

