name: Pyinstaller Windows Executable Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: name_1
      uses: ./.github/actions
      with:
        path: .
    - name: 'name_2'
      uses: actions/upload-artifact@v2
      with:
        name: "Windows Exe"
        path: dist/windows
      # - name: 'Reconnect to action repo'
      #   uses: actions/checkout@v3 

