name: Pyinstaller Windows Executable Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: name_1
      uses: actions/ion-mob-ms@v1
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: name_2
        path: src/dist


