name: Pyinstaller Windows Executable Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'name_1'
        uses: ./.github/actions
        with:
          path: .
      - name: 'name_2'
        uses: actions/upload-artifact@v2
        with:
          path: /home/runner/work/ion-mob-ms/ion-mob-ms/UserInterfaceV2/dist/UI_V2.exe
      # - name: 'Reconnect to action repo'
      #   uses: actions/checkout@v3 

