name: Pyinstaller Windows Executable Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: name_1
        uses: ./github/actions
        with:
          path: src

      - uses: actions/upload-artifact@v2
        with:
          name: name_2
          path: src/dist


